import {
  LogoSvg,
  LogoSmallSvg,
  SearchSvg,
  CloseSvg,
  ArrowRightSvg,
  PressureSvg,
  HumiditySvg,
  SunriseSvg,
  SunsetSvg,
  VisibilitySvg,
  WindSvg,
  DayClearSkySvg,
  NightClearSkySvg,
  DayFewCloudsSvg,
  NightFewCloudsSvg,
  DayScatteredCloudsSvg,
  NightScatteredCloudsSvg,
  DayBrokenCloudsSvg,
  NightBrokenCloudsSvg,
  DayShowerRainSvg,
  NightShowerRainSvg,
  DayRainSvg,
  NightRainSvg,
  DayThunderstormSvg,
  NightThunderstormSvg,
  DaySnowSvg,
  NightSnowSvg,
  DayMistSvg,
  NightMistSvg,
  DeleteSVG,
} from './Svg';

const svgComponents = {
  logo: LogoSvg,
  logoSmall: LogoSmallSvg,
  search: SearchSvg,
  close: CloseSvg,
  delete: DeleteSVG,
  arrowRight: ArrowRightSvg,
  pressure: PressureSvg,
  humidity: HumiditySvg,
  sunrise: SunriseSvg,
  sunset: SunsetSvg,
  visibility: VisibilitySvg,
  wind: WindSvg,
  dayClearSky: DayClearSkySvg,
  nightClearSky: NightClearSkySvg,
  dayFewClouds: DayFewCloudsSvg,
  nightFewClouds: NightFewCloudsSvg,
  dayScatteredClouds: DayScatteredCloudsSvg,
  nightScatteredClouds: NightScatteredCloudsSvg,
  dayBrokenClouds: DayBrokenCloudsSvg,
  nightBrokenClouds: NightBrokenCloudsSvg,
  dayShowerRain: DayShowerRainSvg,
  nightShowerRain: NightShowerRainSvg,
  dayRain: DayRainSvg,
  nightRain: NightRainSvg,
  dayThunderstorm: DayThunderstormSvg,
  nightThunderstorm: NightThunderstormSvg,
  daySnow: DaySnowSvg,
  nightSnow: NightSnowSvg,
  dayMist: DayMistSvg,
  nightMist: NightMistSvg,
};

export const Icon = ({ name = 'close', ...props }) => {
  const SvgComponent = svgComponents[name] || CloseSvg;
  return <SvgComponent {...props} />;
};
